version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
        environment:
          AWS_DEFAULT_REGION: eu-west-1
          SHORT_SHA1: $(echo $CIRCLE_SHA1 | cut -c -7)
          GIT_TAG: $(shell git describe --abbrev=0 --tags | sed 's/\./-/g')
    steps:
      - checkout
      - run:
          name: 'Creating Virtualenv'
          command: |
            virtualenv venv
            pwd
      - restore_cache:
          key: requirements-{{ checksum "requirements.txt" }}
          paths:
            - ~/project/venv
      - run:
          name: 'Installing Requirements'
          command: |
            . ./venv/bin/activate
            pip install -r requirements_tests.txt
      - save_cache:
          key: requirements-{{ checksum "requirements_tests.txt" }}
          paths:
            - ~/project/venv
      - run:
          name: 'Installing Sceptre'
          command: |
            . ./venv/bin/activate
            make install
      # - run:
      #     name: install-docs
      #     command: |
      #       . venv/bin/activatem
      #       make docs
      - run:
          name: Linting
          command: |
            . ./venv/bin/activate
            make lint
      - restore_cache:
          key: tox-requirements-{{ checksum "requirements_tests.txt" }}-{{ checksum "tox.ini" }}
          paths:
            - .tox/py269
            - .tox/py27
            - .tox/py352
            - .tox/py361
      - run:
          name: 'Unit Testing'
          command: |
            . ./venv/bin/activate
            make test-all
      - save_cache:
          key: tox-requirements-{{ checksum "requirements_tests.txt" }}-{{ checksum "tox.ini" }}
          paths:
            - .tox/py269
            - .tox/py27
            - .tox/py352
            - .tox/py361
      - store_test_results:
          path: build/junitxml/pytest/
      - store_artifacts:
          path: build/junitxml/pytest/
      # - run:
      #     name: integration-tests
      #     command: |
      #       . ~/venv/bin/activate
      #       behave integration-tests/ --junit --junit-directory ~/behave/junit.xml
      # - store_test_results:
      #     path: ~/behave
      # - store_artifacts:
      #     path: ~/behave
