version: 2
jobs:
  build:
    parallelism: 4
    docker:
      - image: circleci/python:2.7.13
        environment:
          AWS_DEFAULT_REGION: eu-west-1
          SHORT_SHA1: $(echo $CIRCLE_SHA1 | cut -c -7)
          GIT_TAG: $(shell git describe --abbrev=0 --tags | sed 's/\./-/g')
    steps:
      - checkout
      - restore_cache:
          key: v1-requirements-{{ checksum "requirements.txt" }}
      - run:
          name: 'Creating Virtualenv'
          command: virtualenv venv
      - run:
          name: 'Installing Requirements'
          command: |
            . ./venv/bin/activate
            pip install -r requirements_tests.txt
      - save_cache:
          key: v1-requirements-{{ checksum "requirements.txt" }}
          paths:
            - venv
      - run:
          name: 'Installing Sceptre'
          command: |
            . ./venv/bin/activate
            make install
      # - run:
      #     name: install-docs
      #     command: |
      #       . venv/bin/activatem
      #       make docs
      - run:
          name: Linting
          command: |
            . ./venv/bin/activate
            make lint
      - restore_cache:
          key: v1-tox-requirements-{{ checksum "requirements_tests.txt" }}-{{ checksum "tox.ini" }}
      - run:
          name: 'Unit Testing'
          command: |
            . ./venv/bin/activate
            make test-all
      - save_cache:
          key: v1-tox-requirements-{{ checksum "requirements_tests.txt" }}-{{ checksum "tox.ini" }}
          paths:
            - .tox/py269
            - .tox/py27
            - .tox/py352
            - .tox/py361
      - store_test_results:
          path: build/pytest
      - store_artifacts:
          path: build/pytest
      - run:
          name: 'Integration Testing'
          command: |
            . ./venv/bin/activate
            behave --junit \
                   --junit-directory build/behave \
                   $(circleci tests glob "integration-tests/features/*.feature" | circleci tests split --split-by=timings)
      - store_test_results:
          path: build/behave
      - store_artifacts:
          path: build/behave
